# Generated by Django 2.2.7 on 2019-11-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
